"use client";
import Layout from '@/components/layout/Layout';

const VenderTermsPolicy = () => {
  return (
    <div>
      <Layout content={<TermsOfBusiness />} />
    </div>
  );
};

import React from "react";

const TermsOfBusiness: React.FC = () => {
  return (
    <div className="bg-gray-50 py-8 md:py-12">
      <div className="max-w-7xl mx-auto p-6 md:p-10 bg-white shadow-lg rounded-lg">
        <h1 className="text-3xl font-bold text-gray-600 mb-2">
          VEDIC VAIBHAV TERMS OF BUSINESS FOR SPIRITUAL SERVICE PROVIDERS
        </h1>
        <p className="text-sm text-gray-500 mb-6">
          Last updated: 29th Oct 2025
        </p>

        <p className="text-sm text-gray-600 mb-4 italic">
          This document is an electronic record in terms of Information
          Technology Act, 2000 (“IT Act, 2000”), the applicable rules thereunder
          and the provisions pertaining to electronic records in various
          statutes as amended by the Information Technology Act, 2000. This
          electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </p>
        <p className="text-sm text-gray-600 mb-6 italic">
          This document is published in accordance with the provisions of Rule 3
          (1) of the Information Technology (Intermediary Guidelines and Digital
          Media Ethics Code) Rules, 2021 that require publishing the rules and
          regulations, privacy policy and Terms of Business for access to or
          usage of vedicvaibhav.com website.
        </p>

        {/* --- Section --- */}
        <section className="mb-6">
          <p className="text-gray-700 leading-relaxed mb-4">
            The domain name <strong>vedicvaibhav.com</strong>, including the
            related mobile site and mobile application (here in after referred
            to as “Platform”) is owned and operated by{" "}
            {/* TODO: Add your legal company name here */}
            <strong className="text-red-600">
              VEDICVAIBHAV DOT COM PRIVATE LIMITED{" "}
            </strong>
            , a company incorporated under the Companies Act, 2013.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            For the purpose of the Terms of Business (which shall mean and
            include the memorandum of understanding executed with you) (here in
            after referred to as “ToB”), wherever the context so requires, ‘you’
            and ‘your’ shall relate to any natural or legal person who has
            agreed to become a Spiritual Service Provider / Vendor on the
            Platform by agreeing to provide services on the Platform. The word
            ‘user’ shall imply a Spiritual Service Provider / Vendor on the
            Platform and the terms (‘we’, ‘us’ and ‘our’) shall mean the
            Company.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            Your use of the Platform and the features therein and provisioning
            of any services to the end customer is governed by the agreements
            executed with you, these terms and conditions (ToB) including
            applicable policies available on the Platform, notifications and
            communications sent to you on the Platform which are incorporated
            herein by way of reference. If you transact on the Platform and
            provide services to the end customers who have specifically paid for
            availing your services, you shall be subject to the policies that
            are applicable to the Platform for such a transaction. By mere use
            of the Platform you shall be contracting with the Company, and these
            terms and conditions including the policies constitute your binding
            obligations to the Company.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            We reserve the right, at our sole discretion, to change, modify,
            add, or remove portions of the ToB at any time. We will notify you
            through any of the communication modes as mentioned in this ToB in
            case of any changes or updates to the ToB that materially impact
            your use of the Platform. Your continued use of the Platform
            following the changes or updates will mean that you accept and agree
            to the revisions. As long as you comply with the ToB, we grant you a
            _personal, non-exclusive, non-transferable, and limited privilege to
            enter and use the Platform.
          </p>
          <div className="my-6 p-4 bg-gray-100 rounded-md border border-gray-300">
            <p className="font-semibold text-center text-gray-800">
              ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES
              YOUR AGREEMENT WITH ALL THE TERMS AND CONDITIONS UNDER THE TOB.
              PLEASE READ THE TOB CAREFULLY BEFORE PROCEEDING.
            </p>
            <p className="font-medium text-center text-gray-800 mt-2">
              By implicitly or expressly accepting the ToB, you also accept and
              agree to be bound by all of Company’s policies applicable to you,
              as amended, from time to time.
            </p>
          </div>
        </section>

        {/* --- Section --- */}
        <section className="mb-6">
          <h2 className="text-2xl font-semibold text-gray-800 mt-6 mb-3">
            Spiritual Service Provider / Vendor Eligibility
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            The use of the Platform is available only to persons who can form
            legally binding contracts under the Indian Contract Act, 1872.
            Persons who are "incompetent to contract" within the meaning of the
            Indian Contract Act, 1872, including minors, un-discharged
            insolvents etc. are not eligible to use the Platform. If you are a
            minor i.e. under the age of 18 years, you shall not register as a
            Spiritual Service Provider / Vendor on the Platform, transact or use
            the Platform. The Company reserves the right to terminate your
            registration and/or refuse you access to the Platform if it is
            brought to the Company’s notice or discovered that you are under the
            age of 18 years. If you register as an entity or a legal person, you
            represent that you are duly authorised by the business entity to
            accept the ToB and you have the authority to bind the business
            entity to the ToB.
          </p>
        </section>

        {/* --- Section --- */}
        <section className="mb-6">
          <h2 className="text-2xl font-semibold text-gray-800 mt-6 mb-3">
            Your Account and Registration Obligations
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            In the course of your use of the Platform, you agree to furnish your
            details and information as requested by us from time to time
            including, but not limited to, the following information, to
            register as a Spiritual Service Provider / Vendor :
          </p>
          <ul className="list-disc list-inside mb-4 ml-4 text-gray-700 space-y-2">
            <li>Spiritual Service Provider / Vendor Complete Name</li>
            <li>Spiritual Service Provider / Vendor Complete Address</li>
            <li>
              Spiritual Service Provider / Vendor Complete Contact details:
              <ul className="list-circle list-inside ml-6 mt-1">
                <li>Phone no.</li>
                <li>Email Address</li>
              </ul>
            </li>
            <li>GSTIN (if available)</li>
            <li>PAN</li>
            <li>Pincode</li>
            <li>Pick-up Address</li>
            <li>
              Registered Address - Principal geographic address of its
              headquarters and all branches
            </li>
            <li>Bank A/c Details</li>
            <li>Account Holder Name</li>
            <li>Cancelled Cheque</li>
            <li>Signature</li>
            <li>Display Legal Name</li>
            <li>Legal Name / Trade Name</li>
            <li>Contractual information (SLA)</li>
          </ul>
          <p className="text-gray-700 leading-relaxed mb-4">
            You agree that you have necessary licences and permits for providing
            Spiritual Services to the end customers or devotees on the Platform
            which shall be including but not limited to the licences required by
            all applicable laws. For the purposes of these ToB “Spiritual
            Services” means and include providing spiritual goods and services
            such as ‘prasad’ and the service to perform ‘pooja’ on behalf of the
            end customer.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            You shall remain responsible for maintaining confidentiality of this
            information, and any customer information shared with you pursuant
            to your engagement with the end customer for providing Spiritual
            Services. Further you agree to maintain your display name, login and
            password details. You agree that if you provide any information
            which is untrue, inaccurate, not current, or incomplete or we have
            reasonable grounds to suspect that such information is untrue,
            inaccurate, not current, incomplete, or not in accordance with the
            ToB, we shall have the right to suspend or terminate your account on
            the Platform or indefinitely block you from accessing the Platform
            and terminate any arrangement with the Company.
          </p>
        </section>

        {/* --- Section --- */}
        <section className="mb-6">
          <h2 className="text-2xl font-semibold text-gray-800 mt-6 mb-3">
            Spiritual Service Provider / Vendor Account Deactivation
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            As per our policy, if a Spiritual Service Provider / Vendor requests
            for a closure of the account, the account will be put on hold for a
            period of 90 days to ensure smooth closure of transactions which
            have been made prior to his closure request and this will be
            available to the said Spiritual Service Provider / Vendor for
            downloading payment and taxation reports, if required. After 90
            days, the Spiritual Service Provider / Vendor would be required to
            reach out to us confirming that he has downloaded the reports and
            requesting for a deactivation again. Upon receiving this
            confirmation, the Spiritual Service Provider / Vendor’s account will
            be deactivated provided there are no outstanding Spiritual Services
            are due from the Spiritual Service Provider / Vendor.
          </p>
        </section>

        {/* --- Section --- */}
        <section className="mb-6">
          <h2 className="text-2xl font-semibold text-gray-800 mt-6 mb-3">
            Communications
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            When you use the Platform or send emails, other data, information,
            or communication to us or the end customer, you agree and understand
            that you are communicating through electronic records and you
            consent to receive communications via electronic records from us
            periodically or as and when required. We may communicate with you by
            email or any other mode of communication, electronic or otherwise.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">Consequently:</p>
          <ul className="list-disc list-inside mb-4 ml-4 text-gray-700 space-y-2">
            <li>
              The Company does not determine, advise, have any control, or in
              any way involve itself in the offering or acceptance of the terms
              of the Spiritual Services between you and customers.
            </li>
            <li>
              The Company does not make any representations or warranties
              regarding specifics (such as quality, value, and saleability) of
              the products or Spiritual Services proposed to be sold, offered to
              be sold or purchased on the Platform. Company does not implicitly
              or explicitly support or endorse the sale or purchase of any
              products and Spiritual Services on the Platform. We accept no
              liability for any errors or omissions of third parties in relation
              to the products and Spiritual Services.
            </li>
            <li>
              We are not responsible for any non-performance or breach of any
              contract between you and end customer. We cannot and do not
              guarantee that you and end customers concerned will perform
              transaction(s) concluded on the Platform. Company shall not and is
              not required to mediate or resolve disputes or disagreements
              between you and end customers.
            </li>
            {/* ... Other list items ... */}
            <li>
              The Platform is only a platform that can be utilised by you to
              reach a larger customer base to sell items or provide Spiritual
              Services. The Company only provides a platform for communication
              and acts as an intermediary between the Spiritual Service Provider
              / Vendors and the end customers.
            </li>
          </ul>
        </section>

        {/* --- Section --- */}
        <section className="mb-6">
          <h2 className="text-2xl font-semibold text-gray-800 mt-6 mb-3">
            Use of the Platform
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            You agree and understand that the Company and the Platform merely
            provide hosting services to its registered users and persons
            browsing / visiting the Platform. All items advertised / listed and
            the contents therein are advertised and listed by registered users
            and are third party user generated contents. The Company shall bear
            no responsibility or liability in relation to or arising out of
            third party user generated content. The Company neither originates
            nor modifies the information contained in the transmission. The
            Company is merely an intermediary between end customer and Spiritual
            Service Provider / Vendors.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            You agree, undertake and confirm that your use of the Platform shall
            be strictly governed by the following binding principles and you
            shall not host, display, upload, modify, publish, transmit, update
            or share any information or image which or perform any Spiritual
            Services:
          </p>
          <ul className="list-disc list-inside mb-4 ml-4 text-gray-700 space-y-2">
            <li>belongs to another person and over which you have no right;</li>
            <li>
              is grossly harmful, harassing, blasphemous, defamatory, bigotry,
              obscene, pornographic, pedophilic, libelous, invasive of another’s
              privacy, hateful, or racially, ethnically objectionable,
              disparaging, relating to or encouraging money laundering or
              gambling, or otherwise unlawful in any manner whatever, or
              unlawfully threatening or harassing, including but not to
              ‘indecent representation of women’ within the meaning of the
              Indecent Representation of Women (Prohibition) Act, 1986;
            </li>
            <li>is false, inaccurate or misleading in any way;</li>
            {/* ... Other restrictions ... */}
            <li>impersonates another person;</li>
          </ul>
          {/* ... More content from the "Use of the Platform" section ... */}
          <p className="text-gray-700 leading-relaxed mb-4">
            The personal data shared with the Spiritual Service Provider /
            Vendor should be kept confidential and secure and should be deleted
            post the warranty period. The Spiritual Service Provider / Vendor
            shall not use the customer data for any unauthorised purpose.
          </p>
        </section>

        {/* --- Other Sections --- */}
        <section className="mb-6">
          <h2 className="text-2xl font-semibold text-gray-800 mt-6 mb-3">
            Survival
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            Certain clauses, including but not limited to indemnity,
            confidentiality, intellectual property, and dispute resolution,
            shall survive the termination of this Agreement.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-2xl font-semibold text-gray-800 mt-6 mb-3">
            Indemnity
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            The Vendor agrees to indemnify and hold harmless the Company from
            any claims, losses, damages, costs, or expenses, including legal
            fees, arising due to a breach of the Vendor’s obligations under this
            Agreement or the <strong>Vedic Vaibhav</strong> Policies.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-2xl font-semibold text-gray-800 mt-6 mb-3">
            Governing Law and Jurisdiction
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            The term of this agreement & any disputes arising under this
            agreement shall be governed by the Laws of India and the courts
            having jurisdiction over the registered office of Company will have
            the exclusive jurisdiction to entertain and resolve all the disputes
            between the Parties.
          </p>
        </section>

        {/* ... Repeat for all other sections: Non-Solicitation, IP Rights, Non-Assignability, etc. ... */}

        {/* --- Payment Section --- */}
        <section className="mb-6">
          <h2 className="text-2xl font-semibold text-gray-800 mt-6 mb-3">
            Spiritual Service Provider / Vendor Payment
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            Transactions, transaction price and all commercial terms such as
            delivery, dispatch of products and / or services are as per
            principal to principal bipartite contractual obligations between
            Spiritual Service Provider / Vendors and end customer and the
            payment facility is merely used by Spiritual Service Provider /
            Vendors and end customer to facilitate the completion of
            transactions. Use of the payment facility shall not render the
            LAST_UPDATED Company liable or responsible for non–delivery,
            non-receipt, non-payment, damage, breach of representations and
            warranties, non-provision of after-sales or warranty services or
            fraud as regards the Spiritual Services listed on the Platform.
          </p>
          {/* ... More payment terms ... */}
        </section>

        {/* --- Charges Section --- */}
        <section className="mb-6">
          <h2 className="text-2xl font-semibold text-gray-800 mt-6 mb-3">
            Spiritual Service Provider / Vendor Charges
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            Registration on the Platform is free. The Company does not charge
            any fee for browsing / registering on the Platform. However, for any
            successful booking of Spiritual Service, the Company will charge a
            certain platform fee from the end customer as per its policies for
            facilitating access to Spiritual Services through the Platform.
            Company reserves the right to change its fee policy from time to
            time.
          </p>
          {/* ... More charges terms ... */}
        </section>

        {/* --- Compliance Section --- */}
        <section className="mb-6">
          <h2 className="text-2xl font-semibold text-gray-800 mt-6 mb-3">
            Compliance with Laws
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            Spiritual Service Provider / Vendor acknowledges and undertakes the
            compliance with all applicable laws and also will sign the
            declarations captured in this ToB.
          </p>
          {/* ... All other compliance paragraphs ... */}
          <p className="text-gray-700 leading-relaxed mb-4">
            You shall ensure the authenticity or genuineness of your Spiritual
            Services.
          </p>
          <p className="text-gray-700 leading-relaxed mb-4">
            You shall provide updates on shipment and delivery of products /
            services that are shipped from your premises.
          </p>
        </section>
      </div>
    </div>
  );
};



export default VenderTermsPolicy